# Generated by Django 3.1.3 on 2020-11-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_desc', models.CharField(max_length=128)),
                ('starting_bid', models.FloatField()),
            ],
        ),
    ]
