# Generated by Django 3.1.3 on 2020-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('item_comment', models.ManyToManyField(blank=True, related_name='comments', to='auctions.Listing')),
            ],
        ),
    ]
