# Generated by Django 3.1.3 on 2020-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201201_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('bid_count', models.IntegerField()),
                ('bidder_name', models.CharField(max_length=150)),
            ],
        ),
    ]
