# Generated by Django 3.1.3 on 2020-12-02 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bidder_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddername', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidderitem', to='auctions.listing'),
        ),
    ]
