# Generated by Django 3.1.3 on 2020-12-03 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201202_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 14, 59, 45, 265353)),
            preserve_default=False,
        ),
    ]
