# Generated by Django 3.1.3 on 2020-12-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_item_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item_comment',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commet_item',
            new_name='comment_item',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commet_name',
            new_name='comment_name',
        ),
    ]
