# Generated by Django 3.1.3 on 2020-12-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201204_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
