# Generated by Django 3.1.3 on 2020-12-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201204_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test_field',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
