# Generated by Django 3.1.3 on 2020-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_category_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test_field',
        ),
        migrations.AddField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
